name: Tests - Suite

permissions:
  contents: read
  id-token: write


on:
  push:
    branches: [main]
  pull_request:

jobs:
  main-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]
    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: serapeum-org/github-actions/actions/python-setup/uv@38c111084f99d5ff5f4a1e63bedce48fe33a10c0 # uv/v1.2.1
        with:
          python-version: ${{ matrix.python-version }}
          install-groups: "groups: dev"
          verify-lock: true

      - name: Run Tests
        run: |
          uv run pytest -vvv --cov=src/cleopatra --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0

      - name: test Jupyter notebook
        run: |
          uv run pytest --nbval --nbval-lax --verbose
